services:
    db:
        container_name: pg_container
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
